SPEC = Gem::Specification.new do |spec| 
  spec.name = "bcms_lb_photo_gallery"
  spec.rubyforge_project = spec.name
  spec.version = "1.0.0"
  spec.summary = "A Lb Photo Gallery Module for BrowserCMS"
  spec.author = "Kimmy Chirnside" 
  spec.email = "kimmy.chirnside@gmail.com" 
  spec.files += Dir["app/controllers/**/*"]
  spec.files += Dir["app/models/*"]
  spec.files += Dir["app/helpers/**/*"]
  spec.files += Dir["app/views/cms/**/*"]
  spec.files += Dir["app/views/portlets/photo_gallery/*"]
  spec.files += Dir["app/portlets/**/*"]
  spec.files += Dir["db/migrate/*.rb"]
  spec.files -= Dir["db/migrate/*_browsercms_*.rb"]
  spec.files -= Dir["db/migrate/*_load_seed_data.rb"]
  spec.files += Dir["lib/bcms_lb_photo_gallery.rb"]
  spec.files += Dir["lib/bcms_lb_photo_gallery/*"]
  spec.files += Dir["rails/init.rb"]
  spec.files += Dir["public/bcms/lb_photo_gallery/**/*"]
  spec.has_rdoc = true
  spec.extra_rdoc_files = ["README"]
end
